### ISSUE TITLE
iOS 11 issues

### ISSUE THREAD

**Issue by adamshin** [adamshin/SwiftReorder#11]
On iOS 11, if you drag a cell near the top or bottom of the screen, there are visual jumps and glitches.

Also, automatic cell sizing is enabled by default in iOS 11. This needs to be disabled manually by the library user (see #6). A note should probably be added in the 'usage' section of the readme.

**Comment by colinhumber** [comment]
https://github.com/adamshin/SwiftReorder/pull/13 fixes this.
