### ISSUE TITLE
Are there any options to disable Automatic edge scrolling?

### ISSUE THREAD

**Issue by tungdx** [adamshin/SwiftReorder#14]
I got this issue https://www.youtube.com/watch?v=5vmFZPdEqO0 . Since this issue has not fixed yet. I was just wondering if there are any options to disable Automatic edge scrolling?

**Comment by adamshin** [comment]
Not at the moment, but that's a good idea. I'll look into it and try and publish an update to the pod this weekend.

**Comment by adamshin** [comment]
And done!

**Comment by tungdx** [comment]
Hi @adamshin How can I set disable automatic edge scrolling? or you mean the issue was fixed?

**Comment by adamshin** [comment]
`tableView.reorder.autoScrollEnabled = false`

**Comment by tungdx** [comment]
Hi @adamshin I am using pod to install the library, like this
pod 'SwiftReorder', '~> 3.0'

Could you possibly tell me how can I update to the new version? Thanks

**Comment by adamshin** [comment]
The new version number is 3.1.0 - so change that line to `pod 'SwiftReorder', '~> 3.1'`, run `pod install`, and you should be good.

**Comment by tungdx** [comment]
Thanks @adamshin I did it

**Comment by adamshin** [comment]
@tungdx I just pushed a second update (3.1.1) that fixes the rest of the iOS 11 glitches. If you update to that version, you should be able to turn auto scrolling back on. (`pod update SwiftReorder`)

**Comment by tungdx** [comment]
It works well, thanks @adamshin
