### ISSUE TITLE
Section header bug

### ISSUE THREAD

**Issue by diddledot** [adamshin/SwiftReorder#16]
I have a custom section header cell using `override func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView?`. Some of the sections have no cells in them. When I attempt to drag a cell to an empty section the section header will be a white blank rectangle.

This happens when hovering over an empty section while dragging and persists after a cell is dropped into the empty section. Sometimes it will fix itself after I touch and hold the cell that dropped into the empty section so I can drag it and then drop it immediately without moving it anywhere. 

EDIT:
I managed to work around this bug by creating the section header programatically instead of with the storyboard editor.

**Comment by adamshin** [comment]
Hey - I closed this, then reread your comment. I guess the bug is still present, technically (despite the fact that you found a workaround). Have you found anything else out since then? I'm not sure why section headers would be disappearing... I haven't tested with storyboards myself though.

**Comment by diddledot** [comment]
I scanned your code/commented some parts out that I thought might be causing the issue, but I wasn't able to find anything.

**Comment by AndroidJohnDoe** [comment]
did you solve the problem?

**Comment by VikasPrajapatiSA** [comment]
func tableView(tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? 

Do not return your headerCell, or your reusable identifier. Return the reuseIdentifier.contentView. For me it's: return headerCell!.contentView.
