### ISSUE TITLE
Use of undeclared type 'TableViewReorderDelegate'

### ISSUE THREAD

**Issue by wagng** [adamshin/SwiftReorder#23]
Thanks for sharing a nice library.
I built a custom UITableView and tried to use your library.

- Environments
1. MacOSX
2. XCode 9.2 (9C40b)
3. Swift 4.0

- Installation
```
pod 'SwiftReorder', '~> 4.0'
```

- Code snippets
```
customTableView.reorder.delegate = self
...
extension CustomViewController: TableViewReorderDelegate {
    func tableView(_ tableView: UITableView, reorderRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath) {
        // Update data model
    }
}
```

But I am getting the following errors.
`Value of type 'CustomTableView' has no member 'reorder'`
`Use of undeclared type 'TableViewReorderDelegate'`

Am I missing something? Appreciate any help!

**Comment by adamshin** [comment]
Hi! Have you added `import SwiftReorder` in the source files where you're using the library?

**Comment by wagng** [comment]
Whoops! Sorry my bad. Thank you!
