### ISSUE TITLE
Is it possible to change the Image when begin reordering the cell

### ISSUE THREAD

**Issue by Iamivan1996** [adamshin/SwiftReorder#24]
i am going to display an image, for example a black color of star image, when i trying to reordering the cell, the star will change to yellow color. After finish the reordering, the yellow star will change to black star.

**Comment by matuella** [comment]
@Iamivan1996 could you try to proceed with your flow now that there is an IndexPath when begin the reordering?

**Comment by adamshin** [comment]
I still need to push the updated version to cocoapods. I'll try and get that up later today.

**Comment by Iamivan1996** [comment]
@matuella Yes, there is an indexPath in the function now ,i'm sorry for being late reply cause i'm going to develop android app version.

**Comment by Iamivan1996** [comment]
i found out that why the image is still not changing, when i begin reordering the cell, because of the function on ReorderController.swift<br/>
`func beginReorder(touchPosition: CGPoint){  
    .......
    reorderState = .reordering(context: context)
    delegate.tableViewDidBeginReordering(tableView, at: sourceRow)
`<br/>
delegate.tableViewDidBeginReordering(tableView, at: sourceRow) <-- this should be place in front of `createSnapshotViewForCell(at: sourceRow)`  if the cell is not being updated, the SnapShotView will capture the old cell

How can i update the cell, just call ` super.tableView(tableView, cellForRowAt: indexPath)` on function tableViewDidBeginReordering and create two object on local 
`poistion = indexPath.row`
`isReordering = true`  
if the cell is begin reorder, then change the image that what you want on cellForRowAt function
