### ISSUE TITLE
tableView(_:moveRowAt:to:) method is calling multiple time

### ISSUE THREAD

**Issue by PurpleFrontPvtLtd** [adamshin/SwiftReorder#31]
tableView(_:moveRowAt:to:) method is calling multiple time if going to reorder a cell position with far away cell.

**Comment by adamshin** [comment]
This is a known effect of how the library is implemented. The reorder controller needs to actually move the cells around during a drag-and-drop, meaning the tableview data source has to update live.

If you need to do any heavy lifting (making a server request, etc) after a drag-and-drop is finished, you can use the delegate method `tableViewDidFinishReordering(_:from:to:)`.
