### ISSUE TITLE
Multi-Section TableView reordering

### ISSUE THREAD

**Issue by danlaunch** [adamshin/SwiftReorder#32]
I have a tableview with multiple sections and each section has 1 row.
When I try reordering it crashes saying that 
`attempt to insert row 1 into section 1, but there are only 1 rows in section 1 after the update`
I guess it's because the tableView tries to add tile to the destination section but I return 1 on numberOfRowsInSection.
Is there any solution to solve this issue?
Thanks in advance

**Comment by 1715** [comment]
That's old but might be useful for someone, since the issue hasn't been resolved yet.
I have managed to resolve it by using UITableViewDelegate method as below

```
func tableView(_ tableView: UITableView, targetIndexPathForReorderFromRowAt sourceIndexPath: IndexPath, to proposedDestinationIndexPath: IndexPath) -> IndexPath
{
        if sourceIndexPath.section != proposedDestinationIndexPath.section {
            return sourceIndexPath
        } else {
            return proposedDestinationIndexPath
        }
}
```
This way the table view cell will be able to be reordered only with cells from the same section.

**Comment by imobdevtech** [comment]
> targetIndexPathForReorderFromRowAt

Sir this is not tableview delegate method but it is framework delegate method.

**Comment by 1715** [comment]
> > targetIndexPathForReorderFromRowAt
> 
> Sir this is not tableview delegate method but it is framework delegate method.

@imobdevtech You are totally right, sorry for confusion.

**Comment by adamshin** [comment]
I'm a little late following up on this one, sorry. Dragging cells between sections is definitely possible. The key is to make sure you update your data model in the `tableView(_:UITableView, reorderRowAt:IndexPath, to:IndexPath)` delegate method. This method can be called multiple times during the course of a drag-and-drop gesture; it fires whenever the user drags the cell over a new destination row.

If you don't update your data model (i.e. whatever you're using to determine the return value of `tableView(_:numberOfRowsInSection:)`), you'll run into crashes as mentioned above. You can check out an example [here](https://github.com/adamshin/SwiftReorder/blob/f741ef4a85ea767c17b11b8ab3e455ad4c4ac712/Example/GroupedViewController.swift#L83) in the sample project.
