### ISSUE TITLE
First touch to after reordering is being ignored

### ISSUE THREAD

**Issue by MarkBorazio** [adamshin/SwiftReorder#34]
After reordering a cell, my first touch to select a cell is completely ignored, and didSelectRowAt does not fire. Only once I touch the cell again for a second time does didSelectRowAt gets called.

I did a dirty workaround by grabbing the gesture recognizer and setting `cancelsTouchesInView` to `false`, like so:

`let gestureRecognizer = tableView.gestureRecognizers?.last
  gestureRecognizer?.cancelsTouchesInView = false`

I should add that my table view is within a UIView within a container view. Whether or not that makes a difference, I am not sure.

Should I submit a pull request that automatically sets this value in ReorderController?

**Comment by adamshin** [comment]
Sure – if you're willing to do that, I'll take a look at it and do some testing as well.

**Comment by adamshin** [comment]
Resolved by #36
