### ISSUE TITLE
App is crashing when dragging to a new section

### ISSUE THREAD

**Issue by testproject1234** [adamshin/SwiftReorder#41]
I have 3 section in my tableview. I dont want to reorder the cells from one section to other section. How to avoid dragging one cell from one section to other section.

**Comment by imobdevtech** [comment]
@testproject1234 I came across the same problem, have suggested a solution in #32.

**Comment by adamshin** [comment]
@testproject1234 Yeah, the `tableView(_:UITableView, targetIndexPathForReorderFromRowAt:IndexPath, to:IndexPath)` method is what you'll want to use. If you override it, you can add custom logic for where the selected cell gets dropped.

The example code @imobdevtech linked to should fix your issue:
```
func tableView(_ tableView: UITableView, targetIndexPathForReorderFromRowAt sourceIndexPath: IndexPath, to proposedDestinationIndexPath: IndexPath) -> IndexPath {
    if sourceIndexPath.section != proposedDestinationIndexPath.section {
        return sourceIndexPath
    } else {
        return proposedDestinationIndexPath
    }
}
```
