### ISSUE TITLE
Is it possible to make only the right side of the cell active?

### ISSUE THREAD

**Issue by alexanderkhitev** [adamshin/SwiftReorder#42]
Is it possible to make the user move the cell only if the user touches the right side of the cell?

**Comment by adamshin** [comment]
The library doesn't have that functionality as-is, but you could modify the code and add it pretty easily. You'd need to add a check to `gestureRecognizerShouldBegin(_:UIGestureRecognizer)` in `ReorderController+GestureRecognizer.swift`, so the gesture recognizer only begins if the touch is on the right side of the table view.

**Comment by alexanderkhitev** [comment]
@adamshin Thank you, I started doing that.
