### ISSUE TITLE
Application crashed when moving cell to other section 

### ISSUE THREAD

**Issue by AndroidJohnDoe** [adamshin/SwiftReorder#43]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (7) must be equal to the number of rows contained in that section before the update (7), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

Crash occur, when I cross Section header with cell that I want to get order.

**Comment by adamshin** [comment]
Sounds like you may not be updating your data model in `tableView(_:UITableView, reorderRowAt:IndexPath, to:IndexPath)`. Check out my comment [here](https://github.com/adamshin/SwiftReorder/issues/32#issuecomment-452557776) for an outline of how to resolve this issue. There's some example code in the sample project too which may be helpful.

**Comment by AndroidJohnDoe** [comment]
ok got it, My fault. Resolved it. But can you please give an option for drag and drop in Expand collapse UITableView? I need to implement you this framework on that. What do you think is it implementable?
