### ISSUE TITLE
Swiping row from one section to other section that is collapsed 

### ISSUE THREAD

**Issue by AndroidJohnDoe** [adamshin/SwiftReorder#44]
I have created the expand collapse version of UITableView. now I want to implement your framework on it. The reordering performs very well if UITableView is in expanded form (means Multiple rows in sections), 

But when the sections are collapsed (Means that no rows are being showed inside the section), if I drop row in such section crashes the app, where as if this section is also expanded the row gets drop and reorder. 

How can we implement this ???

**Comment by adamshin** [comment]
Not sure on that one – it depends on how you're implementing your expand/contract behavior. If you're dynamically adding and removing rows, I could see that causing issues. SwiftReorder relies on adding/removing rows as well to make the drag and drop behavior work.

In your `tableView(_:numberOfRowsInSection:)` method, are you returning a hardcoded value of 0 for sections that are collapsed? That would definitely cause a crash when you drag a cell into that section. SwiftReorder is trying to insert a cell there (just an empty spacer cell) but the table view would still see 0 rows after the insertion.

As a workaround, you could override `tableView(_:UITableView, targetIndexPathForReorderFromRowAt:IndexPath, to:IndexPath)` to prevent the user from dragging a cell into a collapsed section. If you need to allow dragging into collapsed sections though, then I'm not sure what the best solution is. It depends on what behavior you expect in that situation.
