### ISSUE TITLE
Dragging a cell to the bottom of a UITableView displays a quirky dark bar while moving to the bottom

### ISSUE THREAD

**Issue by dilizarov** [adamshin/SwiftReorder#5]
Didn't really know how to title it, but you can watch this happen here: https://streamable.com/rjcd

You should be able to see it when I showcase it in the second half of the video.

I haven't looked too deep into the source code, but I'm guessing this might have something to do with the spacer?

**Comment by dilizarov** [comment]
It ended up being that I had a single line separator of that color. When I made the separator a clear color, the line disappeared. I guess in a way that means the issue definitely isn't with the library but it might arise for anyone who decides to use separators in their UITableViews.

**Comment by adamshin** [comment]
@dilizarov Thanks for reaching out. The library tries to be smart with how it handles cell separators, but if the automatic logic isn't working, you can try this:
```swift
tableView.reorder.spacerCellStyle = .hidden
```
That should allow you to keep your separators without them showing up incorrectly. Let me know if that fixes the issue.
