### ISSUE TITLE
Does this library support for the project of objective-c?

### ISSUE THREAD

**Issue by Tim61217** [adamshin/SwiftReorder#53]
This library is very easy-to-use. In some of my projects which build with objective-c also want to use this. Does this library support for the project of objective-c?

**Comment by adamshin** [comment]
Hey sorry for the late reply. I just released a new version of the library (7.1.0) with a couple changes for Objective-C compatibility. You should be able to use it from your objc projects as long as your bridging header, etc are set up properly.

**Comment by adamshin** [comment]
Looks like there are build issues with that last release. SwiftReorder relies on default protocol implementations, which I just realized aren't compatible with Objective-C unfortunately. I'm going to have to back out those changes.

**Comment by Tim61217** [comment]
Ok. Thanks for your reply and effort. I have tried another way to do it on my project. I just think if I can do it in the same way, it's better for maintenance. Have a nice day!
