### ISSUE TITLE
Feature Request: Vibration when dragging cell moves (like current apple feature)

### ISSUE THREAD

**Issue by thejeff77** [adamshin/SwiftReorder#55]
Hey there!

I also allow drag and drop via apple's functionality in edit mode, and am trying to make it match.

One big thing that is different that I think is really cool is that with apple's edit functionality, you feel a slight vibration when your drag moves over a tableviewcell. 

Also - awesome library, clean code. If you want to give me a pointer on where the code detects the cell moving over another cell & re-adjusting I might give this a shot. I'd have to do some research on how to programmatically give that vibration.

**Comment by adamshin** [comment]
Hey, glad you've found the library useful.

For generating haptic feedback, you'll want to use a `UIFeedbackGenerator`– there's various options for different kinds of vibration. You could trigger it in the reorder controller delegate methods, which wouldn't require any modification to the library code.

`tableViewDidBeginReordering(_:at:)` and `tableViewDidFinishReordering(_:from:to:)` get called at the beginning and end of the drag-and-drop, and `tableView(_:reorderRowAt:to)` is called when one cell swaps place with another.

Let me know if that works for you.

**Comment by thejeff77** [comment]
@adamshin thanks for the tips and the quick feedback, I'll give it a try!

**Comment by thejeff77** [comment]
Works like a charm. Thanks for the feedback.
