### ISSUE TITLE
Picking up a cell breaks all other cells

### ISSUE THREAD

**Issue by MohamedElgharbawy** [adamshin/SwiftReorder#57]
I have cells with custom properties, but when I pick up any cell, the rest of them seem to reset and behave unexpectedly. Here is an example of my issue:

https://gfycat.com/bleakconcernedarmadillo

This seems to be a bug unique to this pod, as other ones I have tried do not replicate this issue. Let me know if there's anything you want me to provide to figure this out.

**Comment by adamshin** [comment]
Are you persisting the selection state of your cells outside of the table view? Cells in the table view are reloaded when the drag-and-drop starts, which might explain the issue you're seeing.

**Comment by MohamedElgharbawy** [comment]
Yes, I have the data and selection state saved in an array in the tableVC class

**Comment by adamshin** [comment]
I would set a breakpoint in `cellForRowAtIndexPath` and confirm that the selection state is being set correctly. The reorder controller only reloads cells – it shouldn't be able to reset or modify properties on custom cells. That being said, there may be something else unexpected going on.

**Comment by MohamedElgharbawy** [comment]
Thanks! That fixed it.
