### ISSUE TITLE
Question: Pinch detection

### ISSUE THREAD

**Issue by SirWindfield** [adamshin/SwiftReorder#61]
Hey there!

Sorry to take your issue tracker hostage but I couldn't really find an answer to my question. 
I am currently trying to replicate Procreate's "pinch to merge layers" ListView that you can see in [this](https://www.youtube.com/watch?v=omxlm5oISok) short YouTube video.
I thought I found a solution with your library but after taking a closer look I think it's actually not possible as of now.

I am really new to iOS app creation and was wondering if you could give me some hints on how to implement the above. I think your code is a good starting point. I know for a fact that it is possible to drag and drop multiple ListItems as I found that on the Apple API page somewhere. Maybe it has been done that way, where the pinch triggers somehow the drag and drop action and while you still hold the pinched items your code would somehow kick it, allowing reordering.

I am actually only interested in the pinching part as the ListView that I have in my project does not need reordering.

Sorry for bothering you and any inconveniences I cause :)

**Edit:** I am coming from Android and apparently ListView is called UITableView over here :)

**Comment by adamshin** [comment]
Hey! Looking at that video, I think what you're going for is a little different than what this library provides. But probably simpler too.

I think you could replicate that behavior by adding a pinch gesture recognizer and using it to adjust the position of your onscreen cells. You could set a transform on the `cell.layer`, or maybe a subview's layer, to adjust the cell's visual position. Then if the pinch is released and 'pinched in' beyond a certain threshold, delete those cells and update your table view data source.

They may have done things differently of course. But that's what I'd probably try first.

**Comment by SirWindfield** [comment]
Thanks for your quick response! Would I have to add the pinch gesture recogniser to the UITableView itself or its children?

**Comment by adamshin** [comment]
You'd want it on the UITableView, probably

**Comment by SirWindfield** [comment]
Thank you!
