### ISSUE TITLE
How best to save the order sequence?

### ISSUE THREAD

**Issue by daviddelmonte** [adamshin/SwiftReorder#7]
More of a question than an issue.. But what do you recommend to keep the revised cell order?

Thanks

**Comment by adamshin** [comment]
You're free to implement that how you like. There's some examples in the sample code though - see [here](https://github.com/adamshin/SwiftReorder/blob/master/Example/BasicViewController.swift) for instance.

In that example, the view controller stores an array of items and uses it to populate the table view. It also rearranges those items as necessary in the reorder delegate method.

Let me know if that answers your question!

**Comment by daviddelmonte** [comment]
Got it. Thanks.. I had a core data model, so I save sequences in that.
