### ISSUE TITLE
Swapping with fixed Array sizes

### ISSUE THREAD

**Issue by KarlChow92** [adamshin/SwiftReorder#8]
Hey Adamshin great job on this lib but I got a little issue,

I have 2 sections attached to 2 arrays (1 section per array) where the first section has an array with a fixed size of 1. 

Whenever I drag a cell from the second section to the first section I want the current cell in the first section  to move to the second section if I drop the cell that is being dragged on the first section. Is that possible?

I tried many things such as: calling `func tableView(_ tableView: UITableView, reorderRowAt s: IndexPath, to d: IndexPath)` in the `func tableViewDidFinishReordering(_ tableView: UITableView)` but I constantly get an assertion failed error unfortunately. 

I tried to reorder it after it was dropped, ofcourse I changed my first section array to 2 for this scenario. But again, I get an assertion failed.

**Comment by adamshin** [comment]
Hm, I'm not sure if that's possible if you're using the library without any modifications. If anything, you'd have to update your array in `tableViewDidFinishReordering(:)` and call `tableView(_:moveRowAt:to:)` to update the UI. I tried that though, and it causes issues with the animation code.

You might have to modify the `ReorderController.updateReorder(touchPoint:)` function or `ReorderController.endReorder()`, depending on when you want the cells to be rearranged. Offhand, I'm not sure what changes would be required... I'd have to look into it some more.

Sorry I can't give a better answer right now. Hope that helps.
